In [5]:
import numpy as np

In [2]:
#initialize values

dims = 5
bombs = 2

In [3]:
class Bomb:
  def __init__(self) -> None:
    self.pos_x = None
    self.pos_y = None

In [4]:
# create return array

def pick_bomb_tile(array, dims) -> Bomb:
  bomb = Bomb()
  pos_x = np.random.randint(low=0, high=dims)
  pos_y = np.random.randint(low=0, high=dims)
  if(array[pos_x, pos_y] == 1):
    bomb = pick_bomb_tile(array, dims)
  else:
    array[pos_x, pos_y] = 1
    bomb.pos_x = pos_x
    bomb.pos_y = pos_y
  return bomb


def create_return(dims, bombs) -> tuple[list[Bomb], list[list[int]]]:
  array = np.zeros((dims, dims))
  list_bombs:list[Bomb] = []
  for i in range(bombs):
    list_bombs.append(pick_bomb_tile(array, dims))
  return list_bombs, array

result = create_return(dims, bombs)

print(result[1])


[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]
